Zh hans.lproj
L1ghtmann/IAmLazy-Localization pull request #1
Opened 2023-04-22 16:06 UTC by gujiaming2022

Simplified Chinese

2023-04-22 18:15 UTC, L1ghtmann requested changes
Thank you so much for doing this! Would you mind retaining the file format from the base `en.lproj` (i.e., the spacing, section comments, header, etc). Once that is done, I'll merge. Thanks!

2023-04-23 15:31 UTC, gujiaming2022 commented
Is the format correct?

2023-04-23 15:32 UTC, L1ghtmann commented
Yup, looks great! Did you want to credit yourself at the top? If not, that's fine too.

2023-04-23 16:04 UTC, L1ghtmann approved these changes

2023-04-29 16:00 UTC, L1ghtmann commented on zh-Hans.lproj/Localizable.strings
> +//	Translation by Lightmann
```suggestion
//	Translation by gujiaming2022
```

2023-04-29 16:01 UTC, merged