update zh-Hant.lproj
L1ghtmann/IAmLazy-Localization pull request #14
Opened 2024-04-01 03:56 UTC by Neo1102

Modify the languageCode to comply with Apple's developer documentation.
translate missing string

2024-04-02 15:18 UTC, L1ghtmann commented
Could you possibly link the relevant docs? This change was previously reverted by @olivertzeng (https://github.com/L1ghtmann/IAmLazy-Localization/pull/8)

2024-04-02 23:33 UTC, olivertzeng commented
@Neo1102 @L1ghtmann I've done my reviews on this project. If you have any questions you can ping me here, I'm willing to help.

2024-04-02 23:34 UTC, olivertzeng commented
> Could you possibly link the relevant docs? This change was previously reverted by @olivertzeng (#8)

Again, I prefer zh_TW over zh_Hant but it's personal prefs so it doesn't really matter anyways

2024-04-02 23:37 UTC, olivertzeng commented
Thanks for the translations that I've missed @Neo1102

2024-04-02 23:39 UTC, olivertzeng requested changes
台灣國語是台灣在地的「口音 accent」，不是一種語言
一般我都會稱之為「繁體中文」
或是「繁體中文（台灣）」
還有目前我在台灣論壇內沒有看過有人說插體
請修改成「插件」（或是請提供任何台灣論壇有說「插體」的
![image](https://github.com/L1ghtmann/IAmLazy-Localization/assets/86348833/6c33e9c0-f255-4d1b-8076-2c4f88ffdcf0)
![image](https://github.com/L1ghtmann/IAmLazy-Localization/assets/86348833/c771efba-e9d4-4353-9b79-c3c3edb5be55)
請修改

2024-04-02 23:39 UTC, olivertzeng commented on zh-Hant.lproj/Localizable.strings
> +"Your current jailbreak is %@!" = "您目前的越獄是 %@!";
這我是沒什麼問題
單純個人選擇我尊重（我是習慣「你」）

2024-04-02 23:39 UTC, olivertzeng commented on zh-Hant.lproj/Localizable.strings
> +"Easily backup and restore your tweaks" = "輕鬆備份和恢復您的插體";
輕鬆備份和「回復」（恢復有點像是恢復元氣 應該不太能用在這裡 要改是 optional）您的「插件」（台灣月育使用者幾乎沒在使用「插體」之前在 Dopamine 上有說過）

2024-04-02 23:39 UTC, olivertzeng commented on zh-Hant.lproj/Localizable.strings
> +"Tweak backup completed successfully in %@ seconds!" = "插體備份在 %@ 秒內成功完成！";
「插件」

2024-04-02 23:39 UTC, olivertzeng commented on zh-Hant.lproj/Localizable.strings
>  "Type: %@" = "Type: %@";
「備份類型：%@」

2024-04-02 23:39 UTC, olivertzeng commented on zh-Hant.lproj/Localizable.strings
> +"Design inspiration (re: Electra)" = "設計靈感 (re: Electra)";
「感謝 Electra 越獄提供 GUI 設計靈感」

2024-04-02 23:39 UTC, olivertzeng commented on zh-Hant.lproj/Localizable.strings
> +"Archival functions" = "歸檔功能";
「壓縮」功能

2024-04-03 05:13 UTC, Neo1102 commented
@L1ghtmann 
Here~
https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/LanguageandLocaleIDs/LanguageandLocaleIDs.html

I have now found a Swift document, which is written as zh_TW. 
https://developer.apple.com/documentation/sirikit/registering_custom_vocabulary_with_sirikit/global_vocabulary_reference/localizing_your_vocabulary_for_chinese_dialects/

My guess is that zh-Hant is probably the naming convention during the Objective-C era. There is more than one country using Traditional Chinese, and Swift directly uses the country/region as the language code to solve this problem.
Please decide which naming convention to use, I will follow your decision.

2024-04-03 05:42 UTC, Neo1102 commented
@olivertzeng 
插體這種說法來自皮樂
詞語結構就跟軟體 硬體 韌體一樣

這種附加性質的東西 目前並沒有正式的名稱
有看過 附加元件 擴充功能 增強套件 外掛 等等
插件這種講法 很明顯是支語
拿去Google搜尋 出來的結果更多是中國網站
只是跟素質一樣 從兩千零幾年就有人在講了
很多人不覺得或不知道他是而已

2024-04-03 05:52 UTC, olivertzeng commented
> @olivertzeng 插體這種說法來自皮樂 詞語結構就跟軟體 硬體 韌體一樣
> 
> 這種附加性質的東西 目前並沒有正式的名稱 有看過 附加元件 擴充功能 增強套件 外掛 等等 插件這種講法 很明顯是支語 拿去Google搜尋 出來的結果更多是中國網站 只是跟素質一樣 從兩千零幾年就有人在講了 很多人不覺得或不知道他是而已

https://www.facebook.com/hiraku.tw/posts/365859498231862/
查了一下就找到了
可是我提出幾點異議
1. 那是他自己個人的意見，並不代表權台灣人
2. 即使「插件」這個詞是從中國傳來的，台灣人也早已習慣了，反而講「插體」會聽不懂你在說什麼
不如用「套件」來詮釋 Tweak 好了 因為ios 也是用apt 而apt的packages也叫做套件
你覺得呢？
如果你同意我dopmaine 2的翻譯pr 一併修改

2024-04-03 06:18 UTC, Neo1102 commented
@olivertzeng 
要翻套件 我會把前面兩個字補上
如果要字少一點
我偏好翻 外掛 

至於你說的台灣國語
如果是要表達那種咬字不清的口音
我會直接翻 台灣狗以
要政治正確一點可以改成中華民國國語
繁體中文不止一國在用 現在我不偏好這種翻法
若要遵循Swift的語言碼 跟作者的原文
可以翻 台灣官方語 或直接翻 台灣中文

dopmaine的事就留到那個PR底下再談
這邊就不多說了

2024-04-03 06:52 UTC, olivertzeng commented
外掛也可以
 好啊 可以改成台灣中文

2024-04-03 07:43 UTC, Neo1102 commented on zh-Hant.lproj/Localizable.strings
> +"Your current jailbreak is %@!" = "您目前的越獄是 %@!";
軟體上大多使用尊稱
尤其是商業軟體

2024-04-03 09:42 UTC, olivertzeng approved these changes

2024-04-03 09:43 UTC, olivertzeng commented
@L1ghtmann I've approved the PR

2024-04-03 14:49 UTC, L1ghtmann commented
Thank you both for your assistance! 

> Generally I will call it "Chinese Traditional" or "Chinese Traditional (Taiwan)"

Noted. I will change the key (English version) to "Traditional Chinese" in an update.

2024-04-03 14:50 UTC, L1ghtmann commented
@Neo1102 are you finished with your edits?

2024-04-03 14:51 UTC, olivertzeng commented
> @Neo1102 are you finished with your edits?

he is

2024-04-03 14:53 UTC, Neo1102 commented
> @L1ghtmann Here~ https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/LanguageandLocaleIDs/LanguageandLocaleIDs.html
> 
> I have now found a Swift document, which is written as zh_TW. https://developer.apple.com/documentation/sirikit/registering_custom_vocabulary_with_sirikit/global_vocabulary_reference/localizing_your_vocabulary_for_chinese_dialects/
> 
> My guess is that zh-Hant is probably the naming convention during the Objective-C era. There is more than one country using Traditional Chinese, and Swift directly uses the country/region as the language code to solve this problem. Please decide which naming convention to use, I will follow your decision.

Regarding language code, which naming convention have you decided to use?

2024-04-03 14:56 UTC, L1ghtmann commented
-Hant seems to be more generic, which is fitting given that, as you mentioned, tranditional Chinese is used in places other than just Taiwan.

2024-04-03 15:04 UTC, Neo1102 commented
However, in places that also use Traditional Chinese (such as Hong Kong), there are differences in terminology due to cultural differences. If zh-TW and zh-HK are used, Hong Kong users can maintain their own localized translations. If Hant is used, it will be mixed together.

2024-05-15 16:51 UTC, L1ghtmann commented
Hmmm, taking a look at this again I'm a bit torn. What would you two recommend given the things mentioned? Keep as -TW so that there can be region-specific localizations or generalize?

2024-05-23 03:05 UTC, Neo1102 commented
Yes

2024-05-24 01:48 UTC, L1ghtmann approved these changes
Sounds good. Thanks again to you both!

2024-05-24 01:48 UTC, merged