fix(zh_TW): update strings and added credits
L1ghtmann/IAmLazy-Localization pull request #15
Opened 2024-07-24 01:27 UTC by olivertzeng

2024-07-24 16:34 UTC, L1ghtmann requested changes
Looks good, thanks! Just have one comment

2024-07-24 16:34 UTC, L1ghtmann commented on zh-TW.lproj/Localizable.strings
> +//  Some fixes by Neo1102
Can you move this up with the other contributor

2024-07-25 01:10 UTC, olivertzeng commented
> Looks good, thanks! Just have one comment 

Done

2024-07-25 02:39 UTC, L1ghtmann approved these changes
Thanks again

2024-07-25 02:39 UTC, merged